### ISSUE TITLE
[MainAcitivity]callBottomNavigationのメソッド名修正

### ISSUE THREAD

**Issue by makopy1980** [giglancer/navinavi#3]
- callBottomNavigationのメソッド名を修正する
    - 例えば、setUpBottomNavigationとかsettingBottomNavigationとか直感的に分かりやすいもの
    - callは何かI/Fをコールしたりとかというのを想起させるので、メソッドの内容と合っていない

**Comment by giglancer** [comment]
callBottomNavigation→settingBottomNavigationへと名称変更
