### ISSUE TITLE
[HomeFragment]フラグメント名の変更

### ISSUE THREAD

**Issue by makopy1980** [giglancer/navinavi#4]
- HomeFragmentは画面の持つ機能を表現できていないので、変更を検討してください
    - 後から画面を追加したり遷移を変えたりしたときに、ホームでなくなってしまった場合に、意味が合わなくなってしまいます
    - コードレビュー時には変更しなくてよいと言いましたが、Refactor機能で安全に変換する練習と思って取り組んでみてください！

**Comment by makopy1980** [comment]
紐づいているレイアウトファイル(fragment_home)も同様に変更すること。

**Comment by giglancer** [comment]
HomeFragment→SearchFragmentに変更
それに伴いlayout、navの名称を変更
