### ISSUE TITLE
[HomeFragment]検索APIのパラメータに設定する変数をデータクラス化する

### ISSUE THREAD

**Issue by makopy1980** [giglancer/navinavi#6]
検索APIのパラメータをデータクラス化してください。
HomeFragment内のフィールドとして定義していますが、パラメータの増減があった場合にHomeFragmentを直接いじらなくてはいけないのはメンテナンス性が悪いと思います。
データクラスとして定義することで増減に柔軟に対応できると思います。

**Comment by makopy1980** [comment]
検索履歴としてパラメータを内部DB保存することになるとも思うので、その辺と絡めやすくなると思います。

**Comment by giglancer** [comment]
baseUrl(共通リクエストURL部分), from(出発地), to(到着地), date(日付), time(時間), searchType(departure, firstTrain, lastTrain, arrival) の変数をデータクラス化しました。
