### ISSUE TITLE
[HomeFragment]メソッド名の見直し

### ISSUE THREAD

**Issue by makopy1980** [giglancer/navinavi#7]
HomeFragment内のメソッド全体的にメソッド名の見直しをお願いします。
ネーミングに関しては、下記を参考にしてみてください。
- https://qiita.com/KeithYokoma/items/2193cf79ba76563e3db6
- https://blog.77jp.net/guidelines-for-variables-and-method-names-summary

**Comment by giglancer** [comment]
初期化するためのメソッドにはinitをつけ、bool値を返り値にするメソッドにはisを使用
