### ISSUE TITLE
[HomeFragment]onViewCreated内の整理

### ISSUE THREAD

**Issue by makopy1980** [giglancer/navinavi#8]
onViewCreated内がFatなので整理をお願いします。
ライフサイクル系のメソッドなどはデバッグ時の観点となりやすく、なるべくスリムにして、各タイミングで何をしているか？という見通しをよくしておく必要があります。
また、デバッグ時の実験などで、メソッド内の処理をライフサイクルメソッド間で移動したりすることもあります。

(整理例)
- UI設定
    - コンポーネントごとの設定 
        - コンポーネントの見た目に関する設定
        - コンポーネントのデータソース設定
        - コンポーネントのリスナー設定
- データの設定
    - データクラスごとの初期化や使用準備

**Comment by giglancer** [comment]
導入したトグルボタンのライブラリの初期化、クリックリスナーは一つにまとめ
その二つだけonViewCreatedに記述
